package com.cyopo.billing.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Getter;

@Getter
public class CreateOrderRequest {

    @NotBlank(message = "Plan price ID is required")
    private String planPriceId;

    @NotBlank(message = "Billing cycle is required")
    @Pattern(regexp = "MONTHLY|ANNUAL", message = "Billing cycle must be MONTHLY or ANNUAL")
    private String billingCycle;

    // Generated by frontend at checkout start — prevents duplicate orders
    @NotBlank(message = "Idempotency key is required")
    private String idempotencyKey;

    // Optional — coupon code entered by user
    private String couponCode;

    // Optional — buyer's GSTIN for B2B invoices
    private String gstin;
}