apiVersion: v1
kind: ConfigMap
metadata:
  name: cyopo-config
  namespace: cyopo-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DATABASE_URL: "jdbc:postgresql://cyopo-prod-db.c3qokeuskm9e.ap-south-1.rds.amazonaws.com:5432/cyopo_db"
  DB_USERNAME: "cyopo_admin"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USER: "karthikarji22@gmail.com"
  ALLOWED_ORIGINS: "https://cyopo.com,https://www.cyopo.com"
  FRONTEND_URL: "https://cyopo.com,https://www.cyopo.com"
  CLOUDINARY_CLOUD_NAME: "dnxfschao"