spring:
  application:
    name: cyopo-api
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_schema: auth
  flyway:
    baseline-on-migrate: true
    schemas: auth, template, portfolio
    locations: classpath:db/migration
  spring:
    jackson:
      serialization:
        write-dates-as-timestamps: false
      deserialization:
        fail-on-unknown-properties: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 15MB
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  scheduler:
    weekly-digest-cron: "0 0 8 * * MON"
    coupon-expiry-cron: "0 0 * * * *"
  billing:
    seller-gstin: ""   # add later when you have GSTIN
    razorpay:
      key-id: ${RAZORPAY_KEY_ID:rzp_test_SvduXyrbdlcumu}
      key-secret: ${RAZORPAY_KEY_SECRET:yoursecret}
      webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:https://placard-purgatory-brutishly.ngrok-free.dev}
    scheduler:
      billing-order-expire-cron: "0 */15 * * * *"
      billing-expiry-cron: "0 0 0 * * *"
      billing-reconcile-cron: "0 0 */6 * * *"
      billing-renewal-retry-cron: "0 0 9 * * *"
      billing-ip-masking-cron: "0 0 2 * * *"
server:
  port: 8080

jwt:
  access-token-expiry: 900
  refresh-token-expiry: 604800

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dnxfschao}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

logging:
  level:
    root: WARN
    com.cyopo: INFO
    com.cyopo.auth.security.RateLimitFilter: ERROR
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info