spring:
  application:
    name: cyopo-api
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_schema: auth
  flyway:
    baseline-on-migrate: true
    schemas: auth, template, portfolio
    locations: classpath:db/migration
  spring:
    jackson:
      serialization:
        write-dates-as-timestamps: false
      deserialization:
        fail-on-unknown-properties: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 15MB
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  scheduler:
    weekly-digest-cron: "0 0 8 * * MON"
server:
  port: 8080

jwt:
  access-token-expiry: 900
  refresh-token-expiry: 604800

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dnxfschao}
  api-key:    ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

logging:
  level:
    root: WARN
    com.cyopo: INFO
    com.cyopo.auth.security.RateLimitFilter: ERROR
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info